"""add title column to tasks

Revision ID: 99d6451fb4d6
Revises: 
Create Date: 2025-10-06 17:39:57.666971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d6451fb4d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('task_duration', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('assignee_name', sa.String(), nullable=True))
    op.drop_index('ix_tasks_name', table_name='tasks')
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.create_index('ix_tasks_name', 'tasks', ['name'], unique=False)
    op.drop_column('tasks', 'assignee_name')
    op.drop_column('tasks', 'task_duration')
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
